name: Deploy Telegram Bot

on:
  push:
    branches: [ main ]   # اگر برند اصلی شما master است، این را به master تغییر دهید
  workflow_dispatch:     # همین خط باعث می‌شود دکمه Run workflow در Actions دیده شود

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
      - name: دریافت کد از مخزن
        uses: actions/checkout@v4
        
      - name: نصب Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: نصب کتابخانه‌های مورد نیاز
        run: pip install -r requirements.txt
        
      - name: اجرای ربات
        run: python bot.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
